spring.application.name=company-service

server.port=8081


# ============================
# POSTGRESQL
# ============================

spring.datasource.url=jdbc:postgresql://localhost:5433/wisepick_company

spring.datasource.username=postgres

spring.datasource.password=MonteroM2026


# ============================
# JPA / HIBERNATE
# ============================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect